version: "2"

run:
  timeout: 5m

linters:
  enable:
    - govet
    - ineffassign
    - unused
    - bodyclose
    - durationcheck
    - errname
    - errorlint
    - nilerr
    - predeclared
    - reassign
    - unconvert
  disable:
    - errcheck
    - staticcheck

issues:
  exclude-use-default: true
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - path: _test\.go
      linters:
        - errorlint
