run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - bodyclose
    - durationcheck
    - errname
    - errorlint
    - makezero
    - nilerr
    - predeclared
    - reassign
    - unconvert
    - unparam
  disable:
    - depguard

linters-settings:
  errcheck:
    exclude-functions:
      - (io.Closer).Close
      - (net/http.ResponseWriter).Write

issues:
  exclude-use-default: true
  max-issues-per-linter: 50
  max-same-issues: 10
